### ISSUE TITLE
Look forward to guidance

### ISSUE THREAD

**Issue by surelon** [JayKamat99/mt-multimodal_optimization#1]
Dear author, hello! What is the reason for the error after starting the benchmark_script.sh file according to readme? Look forward to guidance, thank you very much!

(1)./benchmark_script.sh: Line 31:.. /build/t_main: There is no such file or directory

(2) cp: Unable to obtain the file status (stat) of 'data/Benchmarks/2_Two_Pandas' : there is no such file or directory Hello, dear author! What is the reason for the error after starting the benchmark_script.sh file according to readme? Look forward to guidance, thank you very much!

**Comment by JayKamat99** [comment]
Hi @surelon,
Are you on the right branch? Please make sure you are on the `IROS_2022` branch
If you are on the right branch, did the make -jN command run without any errors? That should create the t_main and other executables.

**Comment by surelon** [comment]
Thank you for your reply and send my best wishes

**Comment by JayKamat99** [comment]
Hope your problem was solved. Feel free to reopen the issue if the problem persists.
