### ISSUE TITLE
How to convert obstacles which is represented by 2d occupy map to rai?

### ISSUE THREAD

**Issue by tcjcxy30** [JayKamat99/mt-multimodal_optimization#2]
Hi:
  This work is great and it helpful for me. 
  I want to use it as a global planner for 2d navigation in ros. I want to know how can I add the obstacles to BITKOMO? Maybe I need to add those obstacles into ompl and rai respectively? The obstacles are represened to 1 and the free space is 0 in the 2d occupy map. 
  I can use the State Validity Checking function in ompl, but i don't know how to do in rai.

**Comment by JayKamat99** [comment]
Hi @tcjcxy30,
It's great to hear that you find this work helpful. 
For my experiments, I defined the scenes in Rai, so it implicitly defined a collision checker in KOMO. I used that collision checker to define the state validity checking function in ompl. 
See [this](https://github.com/JayKamat99/mt-multimodal_optimization/blob/2eba582c1e604d433c8ad0c89d78b15c67260a53/examples/Main/main.cpp#L44C1-L44C7) for reference

I do not know if we can define a state collision checker in KOMO if you are not modeling the environment in rai. Maybe you can ask that on the rai repository.

**Comment by tcjcxy30** [comment]
> Hi @tcjcxy30, It's great to hear that you find this work helpful. For my experiments, I defined the scenes in Rai, so it implicitly defined a collision checker in KOMO. I used that collision checker to define the state validity checking function in ompl. See [this](https://github.com/JayKamat99/mt-multimodal_optimization/blob/2eba582c1e604d433c8ad0c89d78b15c67260a53/examples/Main/main.cpp#L44C1-L44C7) for reference
> 
> I do not know if we can define a state collision checker in KOMO if you are not modeling the environment in rai. Maybe you can ask that on the rai repository.

Hi @JayKamat99 ,
Thanks for your reply. I will ask that on rai repository. I have another question that how to implement The Relaxed Edge Checker in your code?

**Comment by JayKamat99** [comment]
Hi @tcjcxy30,
You can find the implementation for the lazy collision checker [here](https://github.com/JayKamat99/ompl/blob/034d33a1e56252db7ecac9c491221f83a247caeb/src/ompl/geometric/planners/informedtrees/src/BITstar.cpp#L866).

I have made a few changes to the BITstar.h and the BITstar.cpp files inside ompl. I have written comments on most of the lines. You should find my modifications by searching for the keyword BITKOMO. 

Feel free to reach out to me if you have any more questions.
